# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.4.0
_src_path: gh:epics-containers/ioc-template
description: ttttt
git_platform: github.com
github_org: gilesknap
name: ioc-lakeshore340
repo_uri: git@github.com:gilesknap/ioc-lakeshore340.git
rtems: false
